### ISSUE TITLE
Smooth animation for slower speeds

### ISSUE THREAD

**Issue by frodefi** [sahilmind/planet_widget#1]
Is it possible to have the animation be smooth also for slower speeds? As you see in this video, it is not so smooth.

https://user-images.githubusercontent.com/993333/211804834-0ad1ed2e-1034-41ef-a130-d1a737443870.mov

**Comment by deep-mindinventory** [comment]
@frodefi share your code snippet so we can identify what changes you made or what references you follow from our code base? Basically we used `TweenAnimationBuilder` so it should work smoothly.
