### ISSUE TITLE
Circle Visibility

### ISSUE THREAD

**Issue by MirzaIkhsan** [sahilmind/planet_widget#2]
I have an issue when using ```CircularRotation``` with ```visibleFirstCircle = false```. If I set it to false the animation won't move

**Comment by mi-raj04** [comment]
@MirzaIkhsan  I tried to regenerate your issues which you're facing please provide the code snippet or share the relevant parts of your implementation where you believe the issue may exist. I'll do my best to assist you in analysing the code and finding a solution.

Feel free to paste the relevant sections of your code here, and I'll be happy to help you troubleshoot the issue.

**Comment by jaydeepkaria-mi** [comment]
As we don't receive any update from your side we are closing this issue as of now. Feel free to open this issue in future.
