### ISSUE TITLE
Dynamic number of Circle

### ISSUE THREAD

**Issue by NguyenNL** [sahilmind/planet_widget#5]
Currently the lib just support 3 Circles, need to Dynamic number of Circle

**Comment by jaydeepkaria-mi** [comment]
Hi @NguyenNL ,

Thank you for reaching out and expressing your interest in extending the functionality of our Flutter package. We appreciate your feedback and understand the need for a dynamic number of circles in our current implementation.

After careful consideration, we want to maintain the simplicity and compatibility of our package to ensure a smooth user experience across various platforms and devices.
